### ISSUE TITLE
Wowhead tooltips with bonus parameter

### ISSUE THREAD

**Issue by sbranly** [bbDKP/bbTips#8]
http://www.wowhead.com/item=115545&bonus=567 for Mythic Loot in WoD
http://www.wowhead.com/item=115545&bonus=562:567 Mythic Warforged
http://www.wowhead.com/item=115545&bonus=561:566 Heroic Warforged

Just some examples

**Comment by wipeer** [comment]
Tooltip [url] tag work but i don't know how to get work [itemico] tag.
[url=http://www.wowhead.com/?item=113906&bonus=560]Gauntlets of Dramatic Blows[/url]
[itemico]113906&bonus=560[/itemico]

**Comment by Sajaki** [comment]
fixed
